### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by cschol** [sumpygump/quantal-audio#1]
Hi,

Are you interested in having your plugin distributed via the official VCV Rack Plugin Manager for all platforms (Windows, Mac, Linux)?

Follow these [instructions](https://github.com/VCVRack/community#adding-your-plugin-to-the-vcv-plugin-manager).

Let me know if you have any questions.

**Comment by sumpygump** [comment]
@cschol Thank you for the invitation. I have created an issue on the community repo https://github.com/VCVRack/community/issues/531
